name: DEPLOYMENT UPTJAA ERP

on:
  push:
    branches:
      - main
      - feature/cd
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/uptjaa-online:${{ github.sha }} .
      - name: login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_USER_TOKEN }}
      - name: docker push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/uptjaa-online:${{ github.sha }}
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.UPTJAA_HOST }}
        username: ${{ secrets.UPTJAA_USERNAME }}
        password: ${{ secrets.UPTJAA_PASSWORD }}
        port: ${{ secrets.UPTJAA_PORT }}
        script: |
          whoami
          docker pull ${{ secrets.DOCKER_USERNAME }}/uptjaa-online:${{ github.sha }}

